server:
  port: 8085

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  flyway:
    url: jdbc:h2:mem:testdb
    user: sa
    password:
  sql:
    init:      mode: always
      platform: h2